[monitoring_servers]
ct-azappmain ansible_connection=local

[domain_controller]
ct-azappdc01 ansible_host=10.10.11.10

[sql_servers]
ct-azappsql01 ansible_host=10.10.21.10
ct-azappsql02 ansible_host=10.10.22.10

[app_servers]
ct-azappvmss01 ansible_host=10.10.11.4 ansible_user=azapp000001\\charlo
ct-azappvmss02 ansible_host=10.10.11.5 ansible_user=azapp000000\\charlo

[app_servers:vars]
ansible_password=ReplaceWithAStrongPassword123!
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_port=5985
ansible_winrm_server_cert_validation=ignore

[windows:children]
domain_controller
sql_servers
app_servers
