[domain_controller]
ct-azappdc01 ansible_host=10.10.11.10

[sql_servers]
ct-azappsql01 ansible_host=10.10.21.10
ct-azappsql02 ansible_host=10.10.22.10

[app_servers]
ct-azappvmss01 ansible_host=10.10.11.4
ct-azappvmss02 ansible_host=10.10.11.5

[windows:children]
domain_controller
sql_servers
app_servers
